version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_consultation_dataset_2019-04-01_to_2019-04-30:
    run: >
      ehrql:v0
        generate-dataset analysis/dataset_definition.py
        --output output/consultation_dataset_2019-04-01_to_2019-04-30.arrow
        --
        --start-date "2019-04-01"
        --end-date "2019-04-30"
    outputs:
      highly_sensitive:
        study_population: output/consultation_dataset_2019-04-01_to_2019-04-30.arrow

  generate_consultation_dataset_2019-05-01_to_2019-05-31:
    run: >
      ehrql:v0
        generate-dataset analysis/dataset_definition.py
        --output output/consultation_dataset_2019-05-01_to_2019-05-31.arrow
        --
        --start-date "2019-05-01"
        --end-date "2019-05-31"
    outputs:
      highly_sensitive:
        study_population: output/consultation_dataset_2019-05-01_to_2019-05-31.arrow

  generate_consultation_dataset_2019-06-01_to_2019-06-30:
    run: >
      ehrql:v0
        generate-dataset analysis/dataset_definition.py
        --output output/consultation_dataset_2019-06-01_to_2019-06-30.arrow
        --
        --start-date "2019-06-01"
        --end-date "2019-06-30"
    outputs:
      highly_sensitive:
        study_population: output/consultation_dataset_2019-06-01_to_2019-06-30.arrow   


  generate_consultation_dataset_2020-04-01_to_2020-04-30:
    run: >
      ehrql:v0
        generate-dataset analysis/dataset_definition.py
        --output output/consultation_dataset_2020-04-01_to_2020-04-30.arrow
        --
        --start-date "2020-04-01"
        --end-date "2020-04-30"
    outputs:
      highly_sensitive:
        study_population: output/consultation_dataset_2020-04-01_to_2020-04-30.arrow

  generate_consultation_dataset_2020-05-01_to_2020-05-31:
    run: >
      ehrql:v0
        generate-dataset analysis/dataset_definition.py
        --output output/consultation_dataset_2020-05-01_to_2020-05-31.arrow
        --
        --start-date "2020-05-01"
        --end-date "2020-05-31"
    outputs:
      highly_sensitive:
        study_population: output/consultation_dataset_2020-05-01_to_2020-05-31.arrow

  generate_consultation_dataset_2020-06-01_to_2020-06-30:
    run: >
      ehrql:v0
        generate-dataset analysis/dataset_definition.py
        --output output/consultation_dataset_2020-06-01_to_2020-06-30.arrow
        --
        --start-date "2020-06-01"
        --end-date "2020-06-30"
    outputs:
      highly_sensitive:
        study_population: output/consultation_dataset_2020-06-01_to_2020-06-30.arrow
  
  summarise_consultation_datasets:
    run: >
      r:latest analysis/summarise_consultation_dataset.R
    needs: [generate_consultation_dataset_2019-04-01_to_2019-04-30, generate_consultation_dataset_2019-05-01_to_2019-05-31, generate_consultation_dataset_2019-06-01_to_2019-06-30
    , generate_consultation_dataset_2020-04-01_to_2020-04-30, generate_consultation_dataset_2020-05-01_to_2020-05-31, generate_consultation_dataset_2020-06-01_to_2020-06-30]
    outputs:
      moderately_sensitive:
        measure_csv: output/data/summary_consultation_dataset.csv

  # summarise_consultation_codes:
  #   run: >
  #     r:latest analysis/investigate_consultation_codes.R
  #   needs: [generate_consultation_dataset_2020-04-01_to_2021-03-31]
  #   outputs:
  #     moderately_sensitive:
  #       measure_csv: output/data/summary_consultation_codes.csv

  visualise_consultation_datasets:
    run: >
      r:latest analysis/visualise_consultation_dataset.R
    needs: [summarise_consultation_datasets]
    outputs:
      moderately_sensitive:
        figure_n_has: output/figures/figure_n_has_consultation_by_age.png
        figure_n_sum: output/figures/figure_n_sum_consultation_by_age.png