version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: >
      ehrql:v0
        generate-dataset analysis/dataset_definition.py
        --output output/dataset.csv
    outputs:
      highly_sensitive:
        study_population: output/dataset.csv
