version: '3.0'

expectations:
  population_size: 5000

actions:

  generate_dataset_fy19to20:
    run: >
      ehrql:v1
        generate-dataset analysis/dataset_definition.py
        --output output/consultation_dataset_2019-04-01_to_2020-03-31.arrow
        --
        --start-date "2019-04-01"
        --end-date "2020-03-31"
    outputs:
      highly_sensitive:
        study_population: output/consultation_dataset_2019-04-01_to_2020-03-31.arrow

  generate_dataset_fy20to21:
    run: >
      ehrql:v1
        generate-dataset analysis/dataset_definition.py
        --output output/consultation_dataset_2020-04-01_to_2021-03-31.arrow
        --
        --start-date "2020-04-01"
        --end-date "2021-03-31"
    outputs:
      highly_sensitive:
        study_population: output/consultation_dataset_2020-04-01_to_2021-03-31.arrow

  generate_dataset_fy21to22:
    run: >
      ehrql:v1
        generate-dataset analysis/dataset_definition.py
        --output output/consultation_dataset_2021-04-01_to_2022-03-31.arrow
        --
        --start-date "2021-04-01"
        --end-date "2022-03-31"
    outputs:
      highly_sensitive:
        study_population: output/consultation_dataset_2021-04-01_to_2022-03-31.arrow

  generate_measures:
    run: >
      ehrql:v1
        generate-measures analysis/measures_definition.py
        --dummy-tables dummy_tables
        --output output/measures/consultation_measures.csv
    outputs:
      moderately_sensitive:
        study_population: output/measures/consultation_measures.csv

  summarise_datasets:
     run: >
       r:latest analysis/summarise_consultation_dataset.R
     needs: [generate_dataset_fy19to20, generate_dataset_fy20to21, generate_dataset_fy21to22]
     outputs:
       moderately_sensitive:
         measure_csv: output/data/summary_consultation_dataset.csv

  binary_regression:
     run: >
       r:latest analysis/binary_regression.R
     needs: [generate_dataset_fy19to20, generate_dataset_fy20to21, generate_dataset_fy21to22]
     outputs:
       moderately_sensitive:
         results: output/results/binary_regression.txt        

  summarise_codes:
    run: >
      r:latest analysis/investigate_consultation_codes.R
    needs: [generate_dataset_fy20to21]
    outputs:
      moderately_sensitive:
        measure_csv: output/data/summary_consultation_codes.csv

  visualise_measures:
     run: >
       r:latest analysis/visualise_consultation_measures.R
     needs: [generate_measures]
     outputs:
       moderately_sensitive:
         figure_ratio: output/figures/plot_ratio_has_consultations.png
         figure_count: output/figures/plot_numerator_count_consultations.png
